<a href="https://colab.research.google.com/github/datakatha/practice/blob/main/DPhi_Python_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# My First colab notebook code 

In [ ]:
print("Hello, DPhi! Today I have executed my very first Python program. Thanks!")

Hello, DPhi! Today I have executed my very first Python program. Thanks!


In [ ]:
x = input("What is your age?")

What is your age?41


In [ ]:
type(x)

str

In [ ]:
x=int(x)

In [ ]:
print(x)

41


In [ ]:
type(x)

int

In [ ]:
x = 36 / 4 * (3 + 2) * 4 + 2
print(x)

182.0


In [ ]:
print(2*2**3)

16


In [ ]:
a=5

In [ ]:
b=16

In [ ]:
c=a+b

In [ ]:
print(c)

21


In [ ]:
x=input("Enter a number-")

Enter a number-5


In [ ]:
y=int(x)**3

In [ ]:
print("The cube of ",x,' is ',str(y))

The cube of  5  is  125


In [ ]:
s = 'Python is easy to learn'
print(s[-5:])
print(s[16:])

learn
o learn


In [ ]:
L = [10, 20, 30, 25, 32, 45, 50]
L.append(20)
L.append(32)
print(L.count(32))

2


In [ ]:
tup=(4,5,6,7,8)
print(tup[4])

8


In [ ]:
 L1 = [10, 20, 30, 25, 32, 45, 50] 
 L2 = [80, 70, 78, 55, 62]
 S1=sum(L1)
 S2=sum(L2)
 print(S1-S2)

-133


In [ ]:
def hi():
  print("hello")

hi()

hello


In [ ]:
def bitcoin_to_USD(btc):
  amount = btc*537
  print("Total $ for ",btc,' bitcoins is :',round(amount,2))

bitcoin_to_USD(2.523)

Total $ for  2.523  bitcoins is : 1354.85


In [ ]:
import numpy

In [3]:
import numpy as np

In [ ]:
def say(message, times=1):
  print(message*times)
say("Hello")
say("World",5)

Hello
WorldWorldWorldWorldWorld


In [ ]:
def fun(x=1,y=2):
  x=x+y
  y+=1
  print(x,y)

fun(y=2,x=1)

3 3


In [36]:
#Create a NumPy array of the first five even numbers.
import numpy as np
count = 0
a = np.empty(0,dtype=int)
for i in range(1,20):
  if i%2 == 0:
    count +=1
    if count <= 5:
      a = np.append(a,i)
   
print(a)

  

[ 2  4  6  8 10]


In [33]:
a.dtype

dtype('float64')

In [37]:
list = [2, 5, 8, 6, 4, 12, 16, 15]
b=np.array(list)
b.ndim

1

In [38]:
c = np.linspace(17,31)
c

array([17.        , 17.28571429, 17.57142857, 17.85714286, 18.14285714,
       18.42857143, 18.71428571, 19.        , 19.28571429, 19.57142857,
       19.85714286, 20.14285714, 20.42857143, 20.71428571, 21.        ,
       21.28571429, 21.57142857, 21.85714286, 22.14285714, 22.42857143,
       22.71428571, 23.        , 23.28571429, 23.57142857, 23.85714286,
       24.14285714, 24.42857143, 24.71428571, 25.        , 25.28571429,
       25.57142857, 25.85714286, 26.14285714, 26.42857143, 26.71428571,
       27.        , 27.28571429, 27.57142857, 27.85714286, 28.14285714,
       28.42857143, 28.71428571, 29.        , 29.28571429, 29.57142857,
       29.85714286, 30.14285714, 30.42857143, 30.71428571, 31.        ])

In [50]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]


In [51]:
a = np.array(L)
a


array([10,  2,  7,  8,  3, 22, 54, 12, 13, 46, 23, 25, 41])

In [52]:
a.sort()
a

array([ 2,  3,  7,  8, 10, 12, 13, 22, 23, 25, 41, 46, 54])

In [53]:
b=np.delete(a,4)
b

array([ 2,  3,  7,  8, 12, 13, 22, 23, 25, 41, 46, 54])

In [47]:
c=np.array(L)
c
c=np.append(c,53)
c

array([10,  2,  7,  8,  3, 22, 54, 12, 13, 46, 23, 25, 41, 53])

In [48]:
c.reshape((2,7))

array([[10,  2,  7,  8,  3, 22, 54],
       [12, 13, 46, 23, 25, 41, 53]])

In [49]:
c.reshape((7,2))

array([[10,  2],
       [ 7,  8],
       [ 3, 22],
       [54, 12],
       [13, 46],
       [23, 25],
       [41, 53]])

In [4]:
c= np.linspace(0,25,num=25,dtype=int)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 25])

In [5]:
c=c.reshape(5,5)

In [66]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 25]])

In [67]:
c[0:2,3:5]

array([[3, 4],
       [8, 9]])

In [9]:
c[1:5:2,0:5:2]


array([[ 5,  7,  9],
       [15, 17, 19]])